services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: amlynx
      POSTGRES_PASSWORD: amlynx
      POSTGRES_DB: amlynx
    ports: ["5432:5432"]
    volumes: ["pg:/var/lib/postgresql/data"]
volumes: { pg: {} }
