name: ci

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: amlynx
          POSTGRES_PASSWORD: amlynx
          POSTGRES_DB: amlynx
        ports: [ "5432:5432" ]
        options: >-
          --health-cmd="pg_isready -U amlynx"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -e .[dev] || pip install -r requirements.txt
          pip install black isort flake8 mypy pytest

      - name: Lint
        run: |
          black --check src tests
          isort --check-only src tests
          flake8 src tests

      - name: Type check
        run: mypy src

      - name: Test
        env:
          DB_HOST: localhost
          DB_USER: amlynx
          DB_PASSWORD: amlynx
          DB_NAME: amlynx
        run: pytest -q
```

---

# 4) Pre-commit hooks

**`.pre-commit-config.yaml`**

```yaml
repos:
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks: [{ id: black }]
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks: [{ id: isort }]
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks: [{ id: flake8 }]
